export interface AlbumGenreItem {
  mainGenre: string;
  subGenre: string;
  international: string;
  domestic: string;
}

export const albumGenreList: AlbumGenreItem[] = [
  {
    mainGenre: "오디오북",
    subGenre: "오디오북",
    international: "Audiobook",
    domestic: "오디오북",
  },
  {
    mainGenre: "가요",
    subGenre: "가요",
    international: "K-pop",
    domestic: "가요",
  },
  {
    mainGenre: "가요",
    subGenre: "발라드(K-pop)",
    international: "K-pop",
    domestic: "발라드",
  },
  {
    mainGenre: "가요",
    subGenre: "댄스(K-pop)",
    international: "K-pop",
    domestic: "댄스",
  },
  {
    mainGenre: "가요",
    subGenre: "댄스",
    international: "Dance",
    domestic: "댄스",
  },
  {
    mainGenre: "가요",
    subGenre: "알앤비/어반(K-pop)",
    international: "K-pop",
    domestic: "알앤비/어반",
  },
  {
    mainGenre: "가요",
    subGenre: "알앤비/어반",
    international: "R&B/Soul",
    domestic: "알앤비/어반",
  },
  {
    mainGenre: "가요",
    subGenre: "락(K-pop)",
    international: "K-pop",
    domestic: "락",
  },
  {
    mainGenre: "가요",
    subGenre: "락(Korean Rock)",
    international: "Korean Rock",
    domestic: "락",
  },
  {
    mainGenre: "가요",
    subGenre: "락(Singer/Songwriter)",
    international: "Singer/Songwriter",
    domestic: "락",
  },
  {
    mainGenre: "가요",
    subGenre: "일렉트로니카(K-pop)",
    international: "K-pop",
    domestic: "일렉트로니카",
  },
  {
    mainGenre: "가요",
    subGenre: "포크(K-pop)",
    international: "K-pop",
    domestic: "포크",
  },
  {
    mainGenre: "가요",
    subGenre: "포크(Singer/Songwriter)",
    international: "Singer/Songwriter",
    domestic: "포크",
  },
  {
    mainGenre: "가요",
    subGenre: "트로트(K-pop)",
    international: "K-pop",
    domestic: "트로트",
  },
  {
    mainGenre: "가요",
    subGenre: "트로트(Korean Folk-Pop)",
    international: "Korean Folk-Pop",
    domestic: "트로트",
  },
  {
    mainGenre: "가요",
    subGenre: "민중가요(K-pop)",
    international: "K-pop",
    domestic: "민중가요",
  },
  {
    mainGenre: "가요",
    subGenre: "민중가요(Korean Folk-Pop)",
    international: "Korean Folk-Pop",
    domestic: "민중가요",
  },
  {
    mainGenre: "가요",
    subGenre: "고전가요(K-pop)",
    international: "K-pop",
    domestic: "고전가요",
  },
  {
    mainGenre: "가요",
    subGenre: "민중가요(Korean Traditional)",
    international: "Korean Traditional",
    domestic: "고전가요",
  },
  {
    mainGenre: "가요",
    subGenre: "인디뮤직(K-pop)",
    international: "K-pop",
    domestic: "인디뮤직",
  },
  {
    mainGenre: "가요",
    subGenre: "인디뮤직(Korean Indie)",
    international: "Korean Indie",
    domestic: "인디뮤직",
  },
  {
    mainGenre: "가요",
    subGenre: "퓨전(K-pop)",
    international: "K-pop",
    domestic: "퓨전",
  },
  {
    mainGenre: "가요",
    subGenre: "랩/힙합(K-pop)",
    international: "K-pop",
    domestic: "랩/힙합",
  },
  {
    mainGenre: "가요",
    subGenre: "랩/힙합(Korean Hip-Hop)",
    international: "Korean Hip-Hop",
    domestic: "랩/힙합",
  },
  {
    mainGenre: "가요",
    subGenre: "어덜트 컨템포러리(K-pop)",
    international: "K-pop",
    domestic: "어덜트 컨템포러리",
  },
  {
    mainGenre: "가요",
    subGenre: "어덜트 컨템포러리",
    international: "Korean Folk-Pop",
    domestic: "어덜트 컨템포러리",
  },
  {
    mainGenre: "가요",
    subGenre: "팝락",
    international: "K-pop",
    domestic: "팝락",
  },
  { mainGenre: "팝", subGenre: "팝", international: "Pop", domestic: "팝" },
  { mainGenre: "팝", subGenre: "팝락", international: "Pop", domestic: "팝락" },
  {
    mainGenre: "팝",
    subGenre: "컨트리",
    international: "Country",
    domestic: "컨트리",
  },
  {
    mainGenre: "팝",
    subGenre: "댄스",
    international: "Dance",
    domestic: "댄스",
  },
  {
    mainGenre: "팝",
    subGenre: "디스코",
    international: "Disco",
    domestic: "디스코",
  },
  {
    mainGenre: "팝",
    subGenre: "뉴 웨이브",
    international: "New Wave",
    domestic: "뉴 웨이브",
  },
  {
    mainGenre: "팝",
    subGenre: "훵크",
    international: "Funk",
    domestic: "훵크",
  },
  {
    mainGenre: "팝",
    subGenre: "알앤비",
    international: "R&B/Soul",
    domestic: "알앤비",
  },
  {
    mainGenre: "팝",
    subGenre: "어덜트 컨템포러리",
    international: "어덜트 컨템포러리",
    domestic: "어덜트 컨템포러리",
  },
  {
    mainGenre: "팝",
    subGenre: "소울",
    international: "R&B/Soul",
    domestic: "소울",
  },
  {
    mainGenre: "팝",
    subGenre: "아카펠라",
    international: "Pop",
    domestic: "아카펠라",
  },
  {
    mainGenre: "팝",
    subGenre: "유로 댄스",
    international: "Dance",
    domestic: "유로 댄스",
  },
  {
    mainGenre: "팝",
    subGenre: "인디 팝",
    international: "Indie Pop",
    domestic: "인디 팝",
  },
  {
    mainGenre: "팝",
    subGenre: "팝스 오케스트라",
    international: "Orchestral",
    domestic: "팝스 오케스트라",
  },
  {
    mainGenre: "팝",
    subGenre: "포크",
    international: "Singer/Songwriter",
    domestic: "포크",
  },
  { mainGenre: "락", subGenre: "락", international: "Rock", domestic: "락" },
  {
    mainGenre: "락",
    subGenre: "얼터너티브 락",
    international: "Rock",
    domestic: "얼터너티브 락",
  },
  {
    mainGenre: "락",
    subGenre: "블루스 락",
    international: "Blues-Rock",
    domestic: "블루스 락",
  },
  {
    mainGenre: "락",
    subGenre: "브릿 락",
    international: "British Invasion",
    domestic: "브릿 락",
  },
  {
    mainGenre: "락",
    subGenre: "하드 락",
    international: "Hard Rock",
    domestic: "하드 락",
  },
  {
    mainGenre: "락",
    subGenre: "헤비 메탈",
    international: "Heavy Metal",
    domestic: "헤비 메탈",
  },
  {
    mainGenre: "락",
    subGenre: "인디",
    international: "Singer/Songwriter",
    domestic: "인디",
  },
  {
    mainGenre: "락",
    subGenre: "인더스트리얼",
    international: "Electronic",
    domestic: "인더스트리얼",
  },
  {
    mainGenre: "락",
    subGenre: "모던 락",
    international: "Rock",
    domestic: "모던 락",
  },
  {
    mainGenre: "락",
    subGenre: "프로그레시브/아트 락",
    international: "Prog-Rock/Art Rock",
    domestic: "프로그레시브/아트 락",
  },
  {
    mainGenre: "락",
    subGenre: "펑크",
    international: "Punk",
    domestic: "펑크",
  },
  {
    mainGenre: "락",
    subGenre: "랩 메탈/하드코어",
    international: "Metal",
    domestic: "랩 메탈/하드코어",
  },
  {
    mainGenre: "락",
    subGenre: "락앤롤",
    international: "Rock & Roll",
    domestic: "락앤롤",
  },
  {
    mainGenre: "락",
    subGenre: "고스 락",
    international: "Goth Rock",
    domestic: "고스 락",
  },
  {
    mainGenre: "락",
    subGenre: "거라지 락",
    international: "Rock",
    domestic: "거라지 락",
  },
  {
    mainGenre: "락",
    subGenre: "글램 락",
    international: "Glam Rock",
    domestic: "글램 락",
  },
  {
    mainGenre: "락",
    subGenre: "멜로딕 메탈",
    international: "Metal",
    domestic: "멜로딕 메탈",
  },
  {
    mainGenre: "락",
    subGenre: "컨트리 락",
    international: "Country",
    domestic: "컨트리 락",
  },
  {
    mainGenre: "락",
    subGenre: "스래시",
    international: "Rock",
    domestic: "스래시",
  },
  {
    mainGenre: "락",
    subGenre: "스카 펑크",
    international: "Punk",
    domestic: "스카 펑크",
  },
  {
    mainGenre: "락",
    subGenre: "프로토 펑크",
    international: "Punk",
    domestic: "프로토 펑크",
  },
  {
    mainGenre: "락",
    subGenre: "싸이키델릭",
    international: "Psychedelic",
    domestic: "싸이키델릭",
  },
  {
    mainGenre: "락",
    subGenre: "포스트 펑크",
    international: "Punk",
    domestic: "포스트 펑크",
  },
  {
    mainGenre: "락",
    subGenre: "포스트 락",
    international: "Rock",
    domestic: "포스트 락",
  },
  { mainGenre: "락", subGenre: "이모", international: "EMO", domestic: "이모" },
  {
    mainGenre: "락",
    subGenre: "데스 메탈",
    international: "Death Metal/Black Metal",
    domestic: "데스 메탈",
  },
  {
    mainGenre: "락",
    subGenre: "블랙 메탈",
    international: "Death Metal/Black Metal",
    domestic: "블랙 메탈",
  },
  {
    mainGenre: "락",
    subGenre: "비주얼 락",
    international: "Rock",
    domestic: "비주얼 락",
  },
  {
    mainGenre: "락",
    subGenre: "스피드 메탈",
    international: "Metal",
    domestic: "스피드 메탈",
  },
  {
    mainGenre: "락",
    subGenre: "포크 락",
    international: "Folk-Rock",
    domestic: "포크 락",
  },
  {
    mainGenre: "재즈",
    subGenre: "애시드/누 재즈",
    international: "Jazz",
    domestic: "애시드/누 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "스윙/빅밴드",
    international: "",
    domestic: "",
  },
  {
    mainGenre: "재즈",
    subGenre: "스윙",
    international: "Swing",
    domestic: "스윙/빅밴드",
  },
  {
    mainGenre: "재즈",
    subGenre: "빅밴드",
    international: "Big Band",
    domestic: "스윙/빅밴드",
  },
  {
    mainGenre: "재즈",
    subGenre: "비밥",
    international: "Bebop",
    domestic: "비밥",
  },
  {
    mainGenre: "재즈",
    subGenre: "쿨 재즈",
    international: "Cool Jazz",
    domestic: "쿨 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "프리 재즈",
    international: "Jazz",
    domestic: "프리 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "퓨전 재즈",
    international: "Fusion",
    domestic: "퓨전 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "하드 밥",
    international: "Hard Bop",
    domestic: "하드 밥",
  },
  {
    mainGenre: "재즈",
    subGenre: "보사노바 재즈",
    international: "Bossa Nova",
    domestic: "보사노바 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "뉴올리언스 재즈",
    international: "Jazz",
    domestic: "뉴올리언스 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "보컬 재즈",
    international: "Vocal Jazz",
    domestic: "보컬 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "컨템포러리 재즈",
    international: "Contemporary Jazz",
    domestic: "컨템포러리 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "크로스오버 재즈",
    international: "Crossover Jazz",
    domestic: "크로스오버 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "스탠다드 재즈",
    international: "Jazz",
    domestic: "스탠다드 재즈",
  },
  {
    mainGenre: "재즈",
    subGenre: "재즈",
    international: "Jazz",
    domestic: "재즈",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "O.S.T(K-pop)",
    international: "K-pop",
    domestic: "O.S.T",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "O.S.T",
    international: "O.S.T",
    domestic: "O.S.T",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "영화음악(K-pop)",
    international: "K-pop",
    domestic: "영화음악",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "영화음악(O.S.T)",
    international: "O.S.T",
    domestic: "영화음악",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "드라마음악(K-pop)",
    international: "K-pop",
    domestic: "드라마음악",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "드라마음악(O.S.T)",
    international: "O.S.T",
    domestic: "드라마음악",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "애니메이션(K-pop)",
    international: "K-pop",
    domestic: "애니메이션",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "애니메이션(O.S.T)",
    international: "O.S.T",
    domestic: "애니메이션",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "뮤지컬(K-pop)",
    international: "K-pop",
    domestic: "뮤지컬",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "뮤지컬(O.S.T)",
    international: "O.S.T",
    domestic: "뮤지컬",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "TV(K-pop)",
    international: "K-pop",
    domestic: "TV",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "TV(O.S.T)",
    international: "O.S.T",
    domestic: "TV",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "게임(K-pop)",
    international: "K-pop",
    domestic: "게임",
  },
  {
    mainGenre: "O.S.T",
    subGenre: "게임(O.S.T)",
    international: "O.S.T",
    domestic: "게임",
  },

  {
    mainGenre: "월드뮤직",
    subGenre: "월드뮤직",
    international: "World",
    domestic: "월드뮤직",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "중국 음악",
    international: "Chinese",
    domestic: "중국 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "칸소네",
    international: "World",
    domestic: "칸소네",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "샹송",
    international: "French Pop",
    domestic: "샹송",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "파두",
    international: "Fado",
    domestic: "파두",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "라틴",
    international: "Latin",
    domestic: "라틴",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "레게",
    international: "Reggae",
    domestic: "레게",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "스카",
    international: "Ska",
    domestic: "스카",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "유럽 음악",
    international: "Europe",
    domestic: "유럽 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "러시아 음악",
    international: "Russian",
    domestic: "러시아 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "아시아 음악",
    international: "Asia",
    domestic: "아시아 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "아프리카 음악",
    international: "African",
    domestic: "아프리카 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "에스닉",
    international: "World",
    domestic: "에스닉",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "월드비트",
    international: "World",
    domestic: "월드비트",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "인도 음악",
    international: "Indian",
    domestic: "인도 음악",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "켈틱/아이리쉬",
    international: "Celtic",
    domestic: "켈틱/아이리쉬",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "탱고",
    international: "Tango",
    domestic: "탱고",
  },
  {
    mainGenre: "월드뮤직",
    subGenre: "중남미 음악",
    international: "Latin",
    domestic: "중남미 음악",
  },
  {
    mainGenre: "일본음악",
    subGenre: "일본음악",
    international: "Japan",
    domestic: "일본음악",
  },
  {
    mainGenre: "일본음악",
    subGenre: "J-팝",
    international: "J-Pop",
    domestic: "J-팝",
  },
  {
    mainGenre: "일본음악",
    subGenre: "J-락",
    international: "J-Pop",
    domestic: "J-락",
  },
  {
    mainGenre: "일본음악",
    subGenre: "J-재즈",
    international: "J-Pop",
    domestic: "J-재즈",
  },
  {
    mainGenre: "일본음악",
    subGenre: "알앤비/힙합",
    international: "J-Pop",
    domestic: "알앤비/힙합",
  },
  {
    mainGenre: "일본음악",
    subGenre: "일렉트로니카",
    international: "J-Pop",
    domestic: "일렉트로니카",
  },
  {
    mainGenre: "일본음악",
    subGenre: "엔카",
    international: "Enka",
    domestic: "엔카",
  },
  {
    mainGenre: "클래식",
    subGenre: "클래식",
    international: "Classical",
    domestic: "클래식",
  },
  {
    mainGenre: "클래식",
    subGenre: "발레음악",
    international: "Classical",
    domestic: "발레음악",
  },
  {
    mainGenre: "클래식",
    subGenre: "고음악",
    international: "Classical",
    domestic: "고음악",
  },
  {
    mainGenre: "클래식",
    subGenre: "관현악",
    international: "Classical",
    domestic: "관현악",
  },
  {
    mainGenre: "클래식",
    subGenre: "협주곡",
    international: "Classical",
    domestic: "협주곡",
  },
  {
    mainGenre: "클래식",
    subGenre: "오페라",
    international: "Opera",
    domestic: "오페라",
  },
  {
    mainGenre: "클래식",
    subGenre: "성악/가곡",
    international: "Classical",
    domestic: "성악/가곡",
  },
  {
    mainGenre: "클래식",
    subGenre: "합창",
    international: "Choral",
    domestic: "합창",
  },
  {
    mainGenre: "클래식",
    subGenre: "실내악",
    international: "Chamber Music",
    domestic: "실내악",
  },
  {
    mainGenre: "클래식",
    subGenre: "클래시컬크로스오버",
    international: "Classical Crossover",
    domestic: "클래시컬크로스오버",
  },
  {
    mainGenre: "클래식",
    subGenre: "현대음악",
    international: "Modern Era",
    domestic: "현대음악",
  },
  {
    mainGenre: "클래식",
    subGenre: "팝페라",
    international: "Classical Crossover",
    domestic: "팝페라",
  },
  {
    mainGenre: "클래식",
    subGenre: "교향곡",
    international: "Classical",
    domestic: "교향곡",
  },
  {
    mainGenre: "클래식",
    subGenre: "종교음악",
    international: "Sacred",
    domestic: "종교음악",
  },
  {
    mainGenre: "클래식",
    subGenre: "독주곡",
    international: "Solo Instrumental",
    domestic: "독주곡",
  },
  {
    mainGenre: "동요",
    subGenre: "동요",
    international: "Children's Music",
    domestic: "동요",
  },
  {
    mainGenre: "동요",
    subGenre: "구연동화",
    international: "Children's Music",
    domestic: "구연동화",
  },
  {
    mainGenre: "동요",
    subGenre: "영어동요",
    international: "Children's Music",
    domestic: "영어동요",
  },
  {
    mainGenre: "동요",
    subGenre: "키즈 팝",
    international: "Children's Music",
    domestic: "키즈 팝",
  },
  {
    mainGenre: "동요",
    subGenre: "전래동요/국악동요",
    international: "Children's Music",
    domestic: "전래동요/국악동요",
  },
  {
    mainGenre: "종교음악",
    subGenre: "종교음악",
    international: "Sacred",
    domestic: "종교음악",
  },
  {
    mainGenre: "종교음악",
    subGenre: "CCM",
    international: "CCM",
    domestic: "CCM",
  },
  {
    mainGenre: "종교음악",
    subGenre: "찬송가",
    international: "Gospel",
    domestic: "찬송가",
  },
  {
    mainGenre: "종교음악",
    subGenre: "성경",
    international: "Sacred",
    domestic: "성경",
  },
  {
    mainGenre: "종교음악",
    subGenre: "불경/찬불가",
    international: "Music",
    domestic: "불경/찬불가",
  },
  {
    mainGenre: "종교음악",
    subGenre: "카톨릭",
    international: "Classical",
    domestic: "카톨릭",
  },
  {
    mainGenre: "종교음악",
    subGenre: "가스펠",
    international: "Gospel",
    domestic: "가스펠",
  },
  {
    mainGenre: "종교음악",
    subGenre: "어린이 찬양",
    international: "Gospel",
    domestic: "어린이 찬양",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "태교음악(Classical)",
    international: "Classical",
    domestic: "태교음악",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "태교음악(Children's Music)",
    international: "Children's Music",
    domestic: "태교음악",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "자장가(Classical)",
    international: "Classical",
    domestic: "자장가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "자장가(Lullabies)",
    international: "Lullabies",
    domestic: "자장가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "기능성 음악",
    international: "기능성 음악",
    domestic: "기능성 음악",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "교가",
    international: "교가",
    domestic: "교가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "CF 음악",
    international: "Soundtrack",
    domestic: "CF 음악",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "시낭송/나레이션",
    international: "시낭송/나레이션",
    domestic: "시낭송/나레이션",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "모바일",
    international: "Ringtones",
    domestic: "모바일",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "캐롤",
    international: "Christmas",
    domestic: "캐롤",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "국가",
    international: "Holiday",
    domestic: "국가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "군가",
    international: "Chant",
    domestic: "군가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "축가",
    international: "Wedding Music",
    domestic: "축가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "효과음",
    international: "Sound Effects",
    domestic: "효과음",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "응원가",
    international: "Chant",
    domestic: "응원가",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "캠페인송",
    international: "캠페인송",
    domestic: "캠페인송",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "뉴에이지",
    international: "New Age",
    domestic: "뉴에이지",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "이지리스닝/인스트루먼탈",
    international: "",
    domestic: "",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "이지리스닝",
    international: "Easy Listening",
    domestic: "이지리스닝/인스트루먼탈",
  },
  {
    mainGenre: "기능성음악",
    subGenre: "인스트루먼탈",
    international: "Instrumental",
    domestic: "이지리스닝/인스트루먼탈",
  },
  {
    mainGenre: "국악",
    subGenre: "국악",
    international: "Korean Traditional",
    domestic: "국악",
  },
  {
    mainGenre: "국악",
    subGenre: "민요",
    international: "Korean Traditional",
    domestic: "민요",
  },
  {
    mainGenre: "국악",
    subGenre: "판소리",
    international: "Korean Traditional",
    domestic: "판소리",
  },
  {
    mainGenre: "국악",
    subGenre: "사물놀이/풍물",
    international: "Korean Traditional",
    domestic: "사물놀이/풍물",
  },
  {
    mainGenre: "국악",
    subGenre: "국악연주",
    international: "Korean Traditional",
    domestic: "국악연주",
  },
  {
    mainGenre: "국악",
    subGenre: "국악 크로스오버",
    international: "Korean Traditional",
    domestic: "국악 크로스오버",
  },
  {
    mainGenre: "국악",
    subGenre: "궁중음악",
    international: "Korean Traditional",
    domestic: "궁중음악",
  },

  {
    mainGenre: "일렉트로니카",
    subGenre: "일렉트로니카",
    international: "Electronic",
    domestic: "일렉트로니카",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "덥",
    international: "Dubstep",
    domestic: "덥",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "하우스",
    international: "House",
    domestic: "하우스",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "라운지",
    international: "Lounge",
    domestic: "라운지",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "레이브",
    international: "Electronic",
    domestic: "레이브",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "앰비언트",
    international: "Ambient",
    domestic: "앰비언트",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "턴테이블리즘",
    international: "Electronic",
    domestic: "턴테이블리즘",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "테크노",
    international: "Techno",
    domestic: "테크노",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "정글/드럼 앤 베이트",
    international: "Jungle/Drum'n'bass",
    domestic: "정글/드럼 앤 베이트",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "트랜스",
    international: "Trance",
    domestic: "트랜스",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "트립합",
    international: "Electronic",
    domestic: "트립합",
  },
  {
    mainGenre: "일렉트로니카",
    subGenre: "클럽/댄스",
    international: "Electronic",
    domestic: "클럽/댄스",
  },
  {
    mainGenre: "힙합",
    subGenre: "힙합",
    international: "Hip Hop/Rap",
    domestic: "힙합",
  },
  {
    mainGenre: "힙합",
    subGenre: "갱스터 랩",
    international: "Gangsta Rap",
    domestic: "갱스터 랩",
  },
  {
    mainGenre: "힙합",
    subGenre: "언더그라운드",
    international: "Underground Rap",
    domestic: "언더그라운드",
  },
  {
    mainGenre: "힙합",
    subGenre: "올드 스쿨 랩",
    international: "Old School Rap",
    domestic: "올드 스쿨 랩",
  },
  {
    mainGenre: "힙합",
    subGenre: "웨스트 코스트 랩",
    international: "West Coast Rap",
    domestic: "웨스트 코스트 랩",
  },
  {
    mainGenre: "힙합",
    subGenre: "이스트 코스트 랩",
    international: "East Coast Rap",
    domestic: "이스트 코스트 랩",
  },
  {
    mainGenre: "힙합",
    subGenre: "턴테이블리즘",
    international: "Hip Hop/Rap",
    domestic: "턴테이블리즘",
  },
  {
    mainGenre: "힙합",
    subGenre: "재즈힙합",
    international: "Hip Hop/Rap",
    domestic: "재즈힙합",
  },
];

export const getAlbumGenreMainGenreList = (): string[] => {
  const uniqueMainGenre = [
    ...new Set(albumGenreList.map((item) => item.mainGenre)),
  ];
  return uniqueMainGenre;
};

export const getAlbumGenreSubGenreList = (
  selectedMainGenre: string,
): string[] => {
  const filteredSubGenre = albumGenreList
    .filter((item) => item.mainGenre === selectedMainGenre)
    .map((item) => item.subGenre);
  return filteredSubGenre;
};
