export interface ArtistRoleItem {
  category1: string;
  category2: string;
}

export const artistRoleList: ArtistRoleItem[] = [
  { category1: "보컬", category2: "랩" },
  { category1: "보컬", category2: "피쳐링" },
  { category1: "보컬", category2: "객원싱어" },
  { category1: "보컬", category2: "소프라노" },
  { category1: "보컬", category2: "메조소프라노" },
  { category1: "보컬", category2: "알토" },
  { category1: "보컬", category2: "테너" },
  { category1: "보컬", category2: "카운터테너" },
  { category1: "보컬", category2: "카스트라토" },
  { category1: "보컬", category2: "바리톤" },
  { category1: "보컬", category2: "베이스 바리톤" },
  { category1: "보컬", category2: "베이스" },
  { category1: "보컬", category2: "합창단" },
  { category1: "보컬", category2: "스캣" },
  { category1: "보컬", category2: "나래이션" },
  { category1: "보컬", category2: "낭송" },
  { category1: "보컬", category2: "독경" },
  { category1: "보컬", category2: "대사" },
  { category1: "보컬", category2: "판소리" },
  { category1: "보컬", category2: "민요" },
  { category1: "보컬", category2: "정가" },
  { category1: "보컬", category2: "허밍" },
  { category1: "보컬", category2: "코러스" },
  { category1: "창작자", category2: "작곡" },
  { category1: "창작자", category2: "작사" },
  { category1: "창작자", category2: "편곡" },
  { category1: "창작자", category2: "리믹스" },
  { category1: "창작자", category2: "샘플링" },
  { category1: "창작자", category2: "시퀀싱" },
  { category1: "창작자", category2: "랩작사" },
  { category1: "창작자", category2: "음악평론(이론)가" },
  { category1: "창작자", category2: "작가" },
  { category1: "창작자", category2: "시인" },
  { category1: "창작자", category2: "채보" },
  { category1: "창작자", category2: "디제이" },
  { category1: "브라스", category2: "트럼펫" },
  { category1: "브라스", category2: "트럼본" },
  { category1: "브라스", category2: "색소폰" },
  { category1: "브라스", category2: "플루트" },
  { category1: "브라스", category2: "클라리넷" },
  { category1: "브라스", category2: "오보에" },
  { category1: "브라스", category2: "피콜로" },
  { category1: "브라스", category2: "호른" },
  { category1: "브라스", category2: "바순" },
  { category1: "브라스", category2: "튜바" },
  { category1: "브라스", category2: "오카리나" },
  { category1: "브라스", category2: "하모니카" },
  { category1: "브라스", category2: "팬플루트" },
  { category1: "브라스", category2: "호각" },
  { category1: "브라스", category2: "피리" },
  { category1: "브라스", category2: "리코더" },
  { category1: "브라스", category2: "코넷" },
  { category1: "브라스", category2: "브라스" },
  { category1: "일렉트로닉", category2: "기타" },
  { category1: "일렉트로닉", category2: "일렉트릭 기타" },
  { category1: "일렉트로닉", category2: "베이스 기타" },
  { category1: "일렉트로닉", category2: "키보드" },
  { category1: "일렉트로닉", category2: "씬디사이저" },
  { category1: "일렉트로닉", category2: "전자피아노" },
  { category1: "일렉트로닉", category2: "전자건반" },
  { category1: "일렉트로닉", category2: "전자바이올린" },
  { category1: "일렉트로닉", category2: "드럼" },
  { category1: "스트링", category2: "어쿠스틱 기타" },
  { category1: "스트링", category2: "클래식 기타" },
  { category1: "스트링", category2: "스트링" },
  { category1: "스트링", category2: "바이올린" },
  { category1: "스트링", category2: "비올라" },
  { category1: "스트링", category2: "만돌린" },
  { category1: "스트링", category2: "반조" },
  { category1: "스트링", category2: "시타" },
  { category1: "스트링", category2: "하프" },
  { category1: "퍼커션", category2: "콩가" },
  { category1: "퍼커션", category2: "봉고" },
  { category1: "퍼커션", category2: "팀파니" },
  { category1: "퍼커션", category2: "베이스 드럼" },
  { category1: "퍼커션", category2: "심벌즈" },
  { category1: "퍼커션", category2: "실로폰" },
  { category1: "퍼커션", category2: "마림바" },
  { category1: "퍼커션", category2: "철금" },
  { category1: "퍼커션", category2: "탬버린" },
  { category1: "퍼커션", category2: "트라이앵글" },
  { category1: "퍼커션", category2: "쉐이커" },
  { category1: "퍼커션", category2: "퍼커션" },
  { category1: "건반", category2: "피아노" },
  { category1: "건반", category2: "파이프 오르간" },
  { category1: "건반", category2: "오르간" },
  { category1: "건반", category2: "멜로디언" },
  { category1: "건반", category2: "아코디언" },
  { category1: "건반", category2: "하프시코드" },
  { category1: "국악기", category2: "가야금" },
  { category1: "국악기", category2: "거문고" },
  { category1: "국악기", category2: "꽹과리" },
  { category1: "국악기", category2: "징" },
  { category1: "국악기", category2: "장구" },
  { category1: "국악기", category2: "북" },
  { category1: "국악기", category2: "대금" },
  { category1: "국악기", category2: "단소" },
  { category1: "국악기", category2: "소금" },
  { category1: "국악기", category2: "해금" },
  { category1: "국악기", category2: "아쟁" },
  { category1: "국악기", category2: "비파" },
  { category1: "국악기", category2: "게피리" },
  { category1: "국악기", category2: "당피리" },
  { category1: "국악기", category2: "향피리" },
  { category1: "국악기", category2: "태평소" },
  { category1: "국악기", category2: "퉁소" },
  { category1: "국악기", category2: "당적" },
  { category1: "국악기", category2: "목탁" },
  { category1: "국악기", category2: "생황" },
  { category1: "국악기", category2: "앙금" },
  { category1: "국악기", category2: "소고" },
  { category1: "국악기", category2: "월금" },
  { category1: "국악기", category2: "중금" },
  { category1: "국악기", category2: "금" },
  { category1: "국악기", category2: "약" },
  { category1: "국악기", category2: "적" },
  { category1: "국악기", category2: "슬" },
  { category1: "국악기", category2: "소" },
  { category1: "국악기", category2: "훈" },
  { category1: "국악기", category2: "고수" },
  { category1: "인스트루먼츠", category2: "인스트루먼츠" },
  { category1: "스탭", category2: "제작자" },
  { category1: "스탭", category2: "프로듀서" },
  { category1: "스탭", category2: "공동 프로듀서" },
  { category1: "스탭", category2: "감독" },
  { category1: "스탭", category2: "조감독" },
  { category1: "스탭", category2: "뮤직 에디터" },
  { category1: "스탭", category2: "뮤직비디오 감독" },
  { category1: "스탭", category2: "기획" },
  { category1: "스탭", category2: "아트디렉터" },
  { category1: "스탭", category2: "자켓 디자이너" },
  { category1: "스탭", category2: "자켓 모델" },
  { category1: "스탭", category2: "포토그래퍼" },
  { category1: "스탭", category2: "매니지먼트" },
  { category1: "스탭", category2: "아티스트 매니져" },
  { category1: "스탭", category2: "스타일리스트" },
  { category1: "스탭", category2: "연출" },
  { category1: "스탭", category2: "조연출" },
  { category1: "스탭", category2: "작가" },
  { category1: "스탭", category2: "기술감독" },
  { category1: "스탭", category2: "카메라감독" },
  { category1: "스탭", category2: "조명" },
  { category1: "스탭", category2: "영상" },
  { category1: "스탭", category2: "편집" },
  { category1: "스탭", category2: "세트디자인" },
  { category1: "스탭", category2: "의상" },
  { category1: "스탭", category2: "분장" },
  { category1: "스탭", category2: "녹음" },
  { category1: "스탭", category2: "음악" },
  { category1: "스탭", category2: "섭외" },
  { category1: "스탭", category2: "소도구" },
  { category1: "스탭", category2: "음향" },
  { category1: "스탭", category2: "무술감독" },
  { category1: "스탭", category2: "촬영감독" },
  { category1: "스탭", category2: "조명감독" },
  { category1: "스탭", category2: "미술" },
  { category1: "스탭", category2: "제작감독" },
  { category1: "스탭", category2: "기획&프로듀서" },
  { category1: "스탭", category2: "섭외" },
  { category1: "스탭", category2: "웹기획" },
  { category1: "스탭", category2: "웹디자인" },
  { category1: "스탭", category2: "웹개발" },
  { category1: "스탭", category2: "기타제작진" },
  { category1: "엔지니어", category2: "엔지니어" },
  { category1: "엔지니어", category2: "어시스턴트 엔지니어" },
  { category1: "엔지니어", category2: "마스터링 엔지니어" },
  { category1: "엔지니어", category2: "믹싱 엔지니어" },
  { category1: "엔지니어", category2: "레코딩 엔지니어" },
  { category1: "엔지니어", category2: "컴퓨터 프로그래밍" },
  { category1: "엔지니어", category2: "보코더" },
  { category1: "직업", category2: "배우" },
  { category1: "직업", category2: "탤런트" },
  { category1: "직업", category2: "모델" },
  { category1: "직업", category2: "방송인" },
  { category1: "직업", category2: "가수" },
  { category1: "직업", category2: "개그맨" },
  { category1: "직업", category2: "MC" },
  { category1: "직업", category2: "진행자" },
  { category1: "직업", category2: "기자" },
  { category1: "직업", category2: "리포터" },
  { category1: "직업", category2: "아나운서" },
  { category1: "직업", category2: "성우" },
  { category1: "직업", category2: "음악평론가" },
  { category1: "직업", category2: "시인" },
  { category1: "직업", category2: "비보이" },
  { category1: "직업", category2: "디자이너" },
  { category1: "직업", category2: "요리사" },
  { category1: "직업", category2: "의사" },
  { category1: "직업", category2: "교수" },
  { category1: "직업", category2: "작가" },
  { category1: "직업", category2: "언론인" },
  { category1: "직업", category2: "정치인" },
  { category1: "직업", category2: "공무원" },
  { category1: "직업", category2: "법조인" },
  { category1: "직업", category2: "군인" },
  { category1: "직업", category2: "기업인" },
  { category1: "직업", category2: "금융인" },
  { category1: "직업", category2: "의료인" },
  { category1: "직업", category2: "문화예술인" },
  { category1: "직업", category2: "스포츠인" },
  { category1: "직업", category2: "종교인" },
  { category1: "직업", category2: "의료인" },
  { category1: "직업", category2: "사회기관 단체인" },
  { category1: "직업", category2: "전문직업인" },
  { category1: "직업", category2: "기타리스트" },

  { category1: "제작/배급", category2: "제작사" },
  { category1: "제작/배급", category2: "기획사" },
  { category1: "제작/배급", category2: "프로모션" },
  { category1: "제작/배급", category2: "배급사" },
  { category1: "제작/배급", category2: "레이블" },
  { category1: "제작/배급", category2: "발매사" },
  { category1: "제작/배급", category2: "유통사" },
  { category1: "제작/배급", category2: "제조사" },
  { category1: "제작/배급", category2: "아티스트 매니지먼트" },
  { category1: "제작/배급", category2: "권리자" },
  { category1: "스튜디오", category2: "레코딩 스튜디오" },
  { category1: "스튜디오", category2: "마스터링 스튜디오" },
  { category1: "스튜디오", category2: "믹싱 스튜디오" },
  { category1: "스튜디오", category2: "포토 스튜디오" },
  { category1: "스튜디오", category2: "프로덕션" },
  { category1: "성악가", category2: "소프라노" },
  { category1: "성악가", category2: "메조소프라노" },
  { category1: "성악가", category2: "알토" },
  { category1: "성악가", category2: "테너" },
  { category1: "성악가", category2: "카운터테너" },
  { category1: "성악가", category2: "카스트라토" },
  { category1: "성악가", category2: "바리톤" },
  { category1: "성악가", category2: "베이스 바리톤" },
  { category1: "성악가", category2: "베이스" },
  { category1: "성악가", category2: "지휘자" },
  { category1: "성악가", category2: "오케스트라" },
  { category1: "성악가", category2: "오페라단" },
  { category1: "성악가", category2: "실내악단" },
];

// category1 번역 키 매핑 (한국어 값 → 번역 키)
export const category1TranslationMap: Record<string, string> = {
  "보컬": "vocal",
  "창작자": "creator",
  "브라스": "brass",
  "일렉트로닉": "electronic",
  "스트링": "strings",
  "퍼커션": "percussion",
  "건반": "keyboard",
  "국악기": "koreanTraditional",
  "인스트루먼츠": "instruments",
  "스탭": "staff",
  "엔지니어": "engineer",
  "직업": "occupation",
  "제작/배급": "productionDistribution",
  "스튜디오": "studio",
  "성악가": "classicalVocal",
};

// category2 번역 키 매핑 (한국어 값 → 번역 키)
export const category2TranslationMap: Record<string, string> = {
  // 보컬
  "랩": "rap",
  "피쳐링": "featuring",
  "객원싱어": "guestSinger",
  "소프라노": "soprano",
  "메조소프라노": "mezzoSoprano",
  "알토": "alto",
  "테너": "tenor",
  "카운터테너": "countertenor",
  "카스트라토": "castrato",
  "바리톤": "baritone",
  "베이스 바리톤": "bassBaritone",
  "베이스": "bass",
  "합창단": "choir",
  "스캣": "scat",
  "나래이션": "narration",
  "낭송": "recitation",
  "독경": "sutraChanting",
  "대사": "dialogue",
  "판소리": "pansori",
  "민요": "folkSong",
  "정가": "jeongga",
  "허밍": "humming",
  "코러스": "chorus",
  // 창작자
  "작곡": "composition",
  "작사": "lyrics",
  "편곡": "arrangement",
  "리믹스": "remix",
  "샘플링": "sampling",
  "시퀀싱": "sequencing",
  "랩작사": "rapLyrics",
  "음악평론(이론)가": "musicCriticTheorist",
  "작가": "writer",
  "시인": "poet",
  "채보": "transcription",
  "디제이": "dj",
  // 브라스
  "트럼펫": "trumpet",
  "트럼본": "trombone",
  "색소폰": "saxophone",
  "플루트": "flute",
  "클라리넷": "clarinet",
  "오보에": "oboe",
  "피콜로": "piccolo",
  "호른": "horn",
  "바순": "bassoon",
  "튜바": "tuba",
  "오카리나": "ocarina",
  "하모니카": "harmonica",
  "팬플루트": "panFlute",
  "호각": "whistle",
  "피리": "piri",
  "리코더": "recorder",
  "코넷": "cornet",
  "브라스": "brassInstrument",
  // 일렉트로닉
  "기타": "guitar",
  "일렉트릭 기타": "electricGuitar",
  "베이스 기타": "bassGuitar",
  "키보드": "keyboardInstrument",
  "씬디사이저": "synthesizer",
  "전자피아노": "electricPiano",
  "전자건반": "electricKeyboard",
  "전자바이올린": "electricViolin",
  "드럼": "drums",
  // 스트링
  "어쿠스틱 기타": "acousticGuitar",
  "클래식 기타": "classicGuitar",
  "스트링": "stringsInstrument",
  "바이올린": "violin",
  "비올라": "viola",
  "만돌린": "mandolin",
  "반조": "banjo",
  "시타": "sitar",
  "하프": "harp",
  // 퍼커션
  "콩가": "conga",
  "봉고": "bongo",
  "팀파니": "timpani",
  "베이스 드럼": "bassDrum",
  "심벌즈": "cymbals",
  "실로폰": "xylophone",
  "마림바": "marimba",
  "철금": "glockenspiel",
  "탬버린": "tambourine",
  "트라이앵글": "triangle",
  "쉐이커": "shaker",
  "퍼커션": "percussionInstrument",
  // 건반
  "피아노": "piano",
  "파이프 오르간": "pipeOrgan",
  "오르간": "organ",
  "멜로디언": "melodion",
  "아코디언": "accordion",
  "하프시코드": "harpsichord",
  // 국악기
  "가야금": "gayageum",
  "거문고": "geomungo",
  "꽹과리": "kkwaenggwari",
  "징": "jing",
  "장구": "janggu",
  "북": "buk",
  "대금": "daegeum",
  "단소": "danso",
  "소금": "sogeum",
  "해금": "haegeum",
  "아쟁": "ajaeng",
  "비파": "bipa",
  "게피리": "gepiri",
  "당피리": "dangpiri",
  "향피리": "hyangpiri",
  "태평소": "taepyeongso",
  "퉁소": "tungso",
  "당적": "dangjeok",
  "목탁": "moktak",
  "생황": "saenghwang",
  "앙금": "anggeum",
  "소고": "sogo",
  "월금": "wolgeum",
  "중금": "junggeum",
  "금": "geum",
  "약": "yak",
  "적": "jeok",
  "슬": "seul",
  "소": "so",
  "훈": "hun",
  "고수": "gosu",
  // 인스트루먼츠
  "인스트루먼츠": "instrumentsRole",
  // 스탭
  "제작자": "producerStaff",
  "프로듀서": "musicProducer",
  "공동 프로듀서": "coProducer",
  "감독": "director",
  "조감독": "assistantDirector",
  "뮤직 에디터": "musicEditor",
  "뮤직비디오 감독": "mvDirector",
  "기획": "planning",
  "아트디렉터": "artDirector",
  "자켓 디자이너": "jacketDesigner",
  "자켓 모델": "jacketModel",
  "포토그래퍼": "photographer",
  "매니지먼트": "management",
  "아티스트 매니져": "artistManager",
  "스타일리스트": "stylist",
  "연출": "directing",
  "조연출": "assistantDirecting",
  "기술감독": "technicalDirector",
  "카메라감독": "cameraDirector",
  "조명": "lighting",
  "영상": "videoProduction",
  "편집": "editing",
  "세트디자인": "setDesign",
  "의상": "costume",
  "분장": "makeup",
  "녹음": "recording",
  "음악": "music",
  "섭외": "casting",
  "소도구": "props",
  "음향": "sound",
  "무술감독": "actionDirector",
  "촬영감독": "cinematographer",
  "조명감독": "lightingDirector",
  "미술": "art",
  "제작감독": "productionDirector",
  "기획&프로듀서": "planningAndProducer",
  "웹기획": "webPlanning",
  "웹디자인": "webDesign",
  "웹개발": "webDevelopment",
  "기타제작진": "otherCrew",
  // 엔지니어
  "엔지니어": "engineerRole",
  "어시스턴트 엔지니어": "assistantEngineer",
  "마스터링 엔지니어": "masteringEngineer",
  "믹싱 엔지니어": "mixingEngineer",
  "레코딩 엔지니어": "recordingEngineer",
  "컴퓨터 프로그래밍": "computerProgramming",
  "보코더": "vocoder",
  // 직업
  "배우": "actor",
  "탤런트": "talent",
  "모델": "model",
  "방송인": "broadcaster",
  "가수": "singer",
  "개그맨": "comedian",
  "MC": "mc",
  "진행자": "host",
  "기자": "journalist",
  "리포터": "reporter",
  "아나운서": "announcer",
  "성우": "voiceActor",
  "음악평론가": "musicCritic",
  "비보이": "bboy",
  "디자이너": "designer",
  "요리사": "chef",
  "의사": "doctor",
  "교수": "professor",
  "언론인": "mediaPerson",
  "정치인": "politician",
  "공무원": "civilServant",
  "법조인": "legalProfessional",
  "군인": "military",
  "기업인": "businessPerson",
  "금융인": "financier",
  "의료인": "medicalProfessional",
  "문화예술인": "culturalArtist",
  "스포츠인": "sportsPerson",
  "종교인": "religiousPerson",
  "사회기관 단체인": "socialOrganization",
  "전문직업인": "professional",
  "기타리스트": "guitarist",
  // 제작/배급
  "제작사": "productionCompany",
  "기획사": "agencyCompany",
  "프로모션": "promotion",
  "배급사": "distributorCompany",
  "레이블": "label",
  "발매사": "publisherCompany",
  "유통사": "distributionCompany",
  "제조사": "manufacturer",
  "아티스트 매니지먼트": "artistManagement",
  "권리자": "rightsHolder",
  // 스튜디오
  "레코딩 스튜디오": "recordingStudio",
  "마스터링 스튜디오": "masteringStudio",
  "믹싱 스튜디오": "mixingStudio",
  "포토 스튜디오": "photoStudio",
  "프로덕션": "production",
  // 성악가 (보컬과 중복되는 것은 이미 위에 포함)
  "지휘자": "conductor",
  "오케스트라": "orchestra",
  "오페라단": "operaCompany",
  "실내악단": "chamberOrchestra",
};

// 구분1 목록만 추출 (중복 제거)
export const getArtistRoleCategory1List = (): string[] => {
  const uniqueCategory1 = [
    ...new Set(artistRoleList.map((item) => item.category1)),
  ];
  return uniqueCategory1;
};

// 선택된 구분1에 해당하는 구분2 목록 추출
export const getArtistRoleCategory2List = (
  selectedCategory1: string,
): string[] => {
  const filteredCategory2 = artistRoleList
    .filter((item) => item.category1 === selectedCategory1)
    .map((item) => item.category2);
  return filteredCategory2;
};
