export interface ArtistRoleItem {
  category1: string;
  category2: string;
}

export const artistRoleList: ArtistRoleItem[] = [
  { category1: "보컬", category2: "랩" },
  { category1: "보컬", category2: "피쳐링" },
  { category1: "보컬", category2: "객원싱어" },
  { category1: "보컬", category2: "소프라노" },
  { category1: "보컬", category2: "메조소프라노" },
  { category1: "보컬", category2: "알토" },
  { category1: "보컬", category2: "테너" },
  { category1: "보컬", category2: "카운터테너" },
  { category1: "보컬", category2: "카스트라토" },
  { category1: "보컬", category2: "바리톤" },
  { category1: "보컬", category2: "베이스 바리톤" },
  { category1: "보컬", category2: "베이스" },
  { category1: "보컬", category2: "합창단" },
  { category1: "보컬", category2: "스캣" },
  { category1: "보컬", category2: "나래이션" },
  { category1: "보컬", category2: "낭송" },
  { category1: "보컬", category2: "독경" },
  { category1: "보컬", category2: "대사" },
  { category1: "보컬", category2: "판소리" },
  { category1: "보컬", category2: "민요" },
  { category1: "보컬", category2: "정가" },
  { category1: "보컬", category2: "허밍" },
  { category1: "보컬", category2: "코러스" },
  { category1: "창작자", category2: "작곡" },
  { category1: "창작자", category2: "작사" },
  { category1: "창작자", category2: "편곡" },
  { category1: "창작자", category2: "리믹스" },
  { category1: "창작자", category2: "샘플링" },
  { category1: "창작자", category2: "시퀀싱" },
  { category1: "창작자", category2: "랩작사" },
  { category1: "창작자", category2: "음악평론(이론)가" },
  { category1: "창작자", category2: "작가" },
  { category1: "창작자", category2: "시인" },
  { category1: "창작자", category2: "채보" },
  { category1: "창작자", category2: "디제이" },
  { category1: "브라스", category2: "트럼펫" },
  { category1: "브라스", category2: "트럼본" },
  { category1: "브라스", category2: "색소폰" },
  { category1: "브라스", category2: "플루트" },
  { category1: "브라스", category2: "클라리넷" },
  { category1: "브라스", category2: "오보에" },
  { category1: "브라스", category2: "피콜로" },
  { category1: "브라스", category2: "호른" },
  { category1: "브라스", category2: "바순" },
  { category1: "브라스", category2: "튜바" },
  { category1: "브라스", category2: "오카리나" },
  { category1: "브라스", category2: "하모니카" },
  { category1: "브라스", category2: "팬플루트" },
  { category1: "브라스", category2: "호각" },
  { category1: "브라스", category2: "피리" },
  { category1: "브라스", category2: "리코더" },
  { category1: "브라스", category2: "코넷" },
  { category1: "브라스", category2: "브라스" },
  { category1: "일렉트로닉", category2: "기타" },
  { category1: "일렉트로닉", category2: "일렉트릭 기타" },
  { category1: "일렉트로닉", category2: "베이스 기타" },
  { category1: "일렉트로닉", category2: "키보드" },
  { category1: "일렉트로닉", category2: "씬디사이저" },
  { category1: "일렉트로닉", category2: "전자피아노" },
  { category1: "일렉트로닉", category2: "전자건반" },
  { category1: "일렉트로닉", category2: "전자바이올린" },
  { category1: "일렉트로닉", category2: "드럼" },
  { category1: "스트링", category2: "어쿠스틱 기타" },
  { category1: "스트링", category2: "클래식 기타" },
  { category1: "스트링", category2: "스트링" },
  { category1: "스트링", category2: "바이올린" },
  { category1: "스트링", category2: "비올라" },
  { category1: "스트링", category2: "만돌린" },
  { category1: "스트링", category2: "반조" },
  { category1: "스트링", category2: "시타" },
  { category1: "스트링", category2: "하프" },
  { category1: "퍼커션", category2: "콩가" },
  { category1: "퍼커션", category2: "봉고" },
  { category1: "퍼커션", category2: "팀파니" },
  { category1: "퍼커션", category2: "베이스 드럼" },
  { category1: "퍼커션", category2: "심벌즈" },
  { category1: "퍼커션", category2: "실로폰" },
  { category1: "퍼커션", category2: "마림바" },
  { category1: "퍼커션", category2: "철금" },
  { category1: "퍼커션", category2: "탬버린" },
  { category1: "퍼커션", category2: "트라이앵글" },
  { category1: "퍼커션", category2: "쉐이커" },
  { category1: "퍼커션", category2: "퍼커션" },
  { category1: "건반", category2: "피아노" },
  { category1: "건반", category2: "파이프 오르간" },
  { category1: "건반", category2: "오르간" },
  { category1: "건반", category2: "멜로디언" },
  { category1: "건반", category2: "아코디언" },
  { category1: "건반", category2: "하프시코드" },
  { category1: "국악기", category2: "가야금" },
  { category1: "국악기", category2: "거문고" },
  { category1: "국악기", category2: "꽹과리" },
  { category1: "국악기", category2: "징" },
  { category1: "국악기", category2: "장구" },
  { category1: "국악기", category2: "북" },
  { category1: "국악기", category2: "대금" },
  { category1: "국악기", category2: "단소" },
  { category1: "국악기", category2: "소금" },
  { category1: "국악기", category2: "해금" },
  { category1: "국악기", category2: "아쟁" },
  { category1: "국악기", category2: "비파" },
  { category1: "국악기", category2: "게피리" },
  { category1: "국악기", category2: "당피리" },
  { category1: "국악기", category2: "향피리" },
  { category1: "국악기", category2: "태평소" },
  { category1: "국악기", category2: "퉁소" },
  { category1: "국악기", category2: "당적" },
  { category1: "국악기", category2: "목탁" },
  { category1: "국악기", category2: "생황" },
  { category1: "국악기", category2: "앙금" },
  { category1: "국악기", category2: "소고" },
  { category1: "국악기", category2: "월금" },
  { category1: "국악기", category2: "중금" },
  { category1: "국악기", category2: "금" },
  { category1: "국악기", category2: "약" },
  { category1: "국악기", category2: "적" },
  { category1: "국악기", category2: "슬" },
  { category1: "국악기", category2: "소" },
  { category1: "국악기", category2: "훈" },
  { category1: "국악기", category2: "고수" },
  { category1: "인스트루먼츠", category2: "인스트루먼츠" },
  { category1: "스탭", category2: "제작자" },
  { category1: "스탭", category2: "프로듀서" },
  { category1: "스탭", category2: "공동 프로듀서" },
  { category1: "스탭", category2: "감독" },
  { category1: "스탭", category2: "조감독" },
  { category1: "스탭", category2: "뮤직 에디터" },
  { category1: "스탭", category2: "뮤직비디오 감독" },
  { category1: "스탭", category2: "기획" },
  { category1: "스탭", category2: "아트디렉터" },
  { category1: "스탭", category2: "자켓 디자이너" },
  { category1: "스탭", category2: "자켓 모델" },
  { category1: "스탭", category2: "포토그래퍼" },
  { category1: "스탭", category2: "매니지먼트" },
  { category1: "스탭", category2: "아티스트 매니져" },
  { category1: "스탭", category2: "스타일리스트" },
  { category1: "스탭", category2: "연출" },
  { category1: "스탭", category2: "조연출" },
  { category1: "스탭", category2: "작가" },
  { category1: "스탭", category2: "기술감독" },
  { category1: "스탭", category2: "카메라감독" },
  { category1: "스탭", category2: "조명" },
  { category1: "스탭", category2: "영상" },
  { category1: "스탭", category2: "편집" },
  { category1: "스탭", category2: "세트디자인" },
  { category1: "스탭", category2: "의상" },
  { category1: "스탭", category2: "분장" },
  { category1: "스탭", category2: "녹음" },
  { category1: "스탭", category2: "음악" },
  { category1: "스탭", category2: "섭외" },
  { category1: "스탭", category2: "소도구" },
  { category1: "스탭", category2: "음향" },
  { category1: "스탭", category2: "무술감독" },
  { category1: "스탭", category2: "촬영감독" },
  { category1: "스탭", category2: "조명감독" },
  { category1: "스탭", category2: "미술" },
  { category1: "스탭", category2: "제작감독" },
  { category1: "스탭", category2: "기획&프로듀서" },
  { category1: "스탭", category2: "섭외" },
  { category1: "스탭", category2: "웹기획" },
  { category1: "스탭", category2: "웹디자인" },
  { category1: "스탭", category2: "웹개발" },
  { category1: "스탭", category2: "기타제작진" },
  { category1: "엔지니어", category2: "엔지니어" },
  { category1: "엔지니어", category2: "어시스턴트 엔지니어" },
  { category1: "엔지니어", category2: "마스터링 엔지니어" },
  { category1: "엔지니어", category2: "믹싱 엔지니어" },
  { category1: "엔지니어", category2: "레코딩 엔지니어" },
  { category1: "엔지니어", category2: "컴퓨터 프로그래밍" },
  { category1: "엔지니어", category2: "보코더" },
  { category1: "직업", category2: "배우" },
  { category1: "직업", category2: "탤런트" },
  { category1: "직업", category2: "모델" },
  { category1: "직업", category2: "방송인" },
  { category1: "직업", category2: "가수" },
  { category1: "직업", category2: "개그맨" },
  { category1: "직업", category2: "MC" },
  { category1: "직업", category2: "진행자" },
  { category1: "직업", category2: "기자" },
  { category1: "직업", category2: "리포터" },
  { category1: "직업", category2: "아나운서" },
  { category1: "직업", category2: "성우" },
  { category1: "직업", category2: "음악평론가" },
  { category1: "직업", category2: "시인" },
  { category1: "직업", category2: "비보이" },
  { category1: "직업", category2: "디자이너" },
  { category1: "직업", category2: "요리사" },
  { category1: "직업", category2: "의사" },
  { category1: "직업", category2: "교수" },
  { category1: "직업", category2: "작가" },
  { category1: "직업", category2: "언론인" },
  { category1: "직업", category2: "정치인" },
  { category1: "직업", category2: "공무원" },
  { category1: "직업", category2: "법조인" },
  { category1: "직업", category2: "군인" },
  { category1: "직업", category2: "기업인" },
  { category1: "직업", category2: "금융인" },
  { category1: "직업", category2: "의료인" },
  { category1: "직업", category2: "문화예술인" },
  { category1: "직업", category2: "스포츠인" },
  { category1: "직업", category2: "종교인" },
  { category1: "직업", category2: "의료인" },
  { category1: "직업", category2: "사회기관 단체인" },
  { category1: "직업", category2: "전문직업인" },
  { category1: "직업", category2: "기타리스트" },
  { category1: "기타", category2: "지휘" },
  { category1: "기타", category2: "스크래치" },
  { category1: "기타", category2: "비트박스" },
  { category1: "기타", category2: "고수" },
  { category1: "기타", category2: "디제이" },
  { category1: "기타", category2: "오케스트라" },
  { category1: "기타", category2: "오페라단" },
  { category1: "기타", category2: "실내악단" },
  { category1: "기타", category2: "교향악단" },
  { category1: "기타", category2: "연주단" },
  { category1: "제작/배급", category2: "제작사" },
  { category1: "제작/배급", category2: "기획사" },
  { category1: "제작/배급", category2: "프로모션" },
  { category1: "제작/배급", category2: "배급사" },
  { category1: "제작/배급", category2: "레이블" },
  { category1: "제작/배급", category2: "발매사" },
  { category1: "제작/배급", category2: "유통사" },
  { category1: "제작/배급", category2: "제조사" },
  { category1: "제작/배급", category2: "아티스트 매니지먼트" },
  { category1: "제작/배급", category2: "권리사" },
  { category1: "스튜디오", category2: "레코딩 스튜디오" },
  { category1: "스튜디오", category2: "마스터링 스튜디오" },
  { category1: "스튜디오", category2: "믹싱 스튜디오" },
  { category1: "스튜디오", category2: "포토 스튜디오" },
  { category1: "스튜디오", category2: "프로덕션" },
  { category1: "성악가", category2: "소프라노" },
  { category1: "성악가", category2: "메조소프라노" },
  { category1: "성악가", category2: "알토" },
  { category1: "성악가", category2: "테너" },
  { category1: "성악가", category2: "카운터테너" },
  { category1: "성악가", category2: "카스트라토" },
  { category1: "성악가", category2: "바리톤" },
  { category1: "성악가", category2: "베이스 바리톤" },
  { category1: "성악가", category2: "베이스" },
  { category1: "성악가", category2: "지휘자" },
  { category1: "성악가", category2: "오케스트라" },
  { category1: "성악가", category2: "오페라단" },
  { category1: "성악가", category2: "실내악단" },
];

// 구분1 목록만 추출 (중복 제거)
export const getArtistRoleCategory1List = (): string[] => {
  const uniqueCategory1 = [
    ...new Set(artistRoleList.map((item) => item.category1)),
  ];
  return uniqueCategory1;
};

// 선택된 구분1에 해당하는 구분2 목록 추출
export const getArtistRoleCategory2List = (
  selectedCategory1: string,
): string[] => {
  const filteredCategory2 = artistRoleList
    .filter((item) => item.category1 === selectedCategory1)
    .map((item) => item.category2);
  return filteredCategory2;
};
