export interface CountryItem {
  name: string;
  countryCode: string;
}

export const countryList: CountryItem[] = [
  { name: "대한민국", countryCode: "KR" },
  { name: "가나", countryCode: "GH" },
  { name: "가봉", countryCode: "GA" },
  { name: "가이아나", countryCode: "GY" },
  { name: "감비아", countryCode: "GM" },
  { name: "건지섬", countryCode: "GG" },
  { name: "과들루프", countryCode: "GP" },
  { name: "과테말라", countryCode: "GT" },
  { name: "괌", countryCode: "GU" },
  { name: "그레나다", countryCode: "GD" },
  { name: "그리스", countryCode: "GR" },
  { name: "그린란드", countryCode: "GL" },
  { name: "기니", countryCode: "GN" },
  { name: "기니비사우", countryCode: "GW" },
  { name: "나미비아", countryCode: "NA" },
  { name: "나우루", countryCode: "NR" },
  { name: "나이지리아", countryCode: "NG" },
  { name: "남극", countryCode: "AQ" },
  { name: "남수단", countryCode: "SS" },
  { name: "남아프리카 공화국", countryCode: "ZA" },
  { name: "네덜란드", countryCode: "NL" },
  { name: "네팔", countryCode: "NP" },
  { name: "노르웨이", countryCode: "NO" },
  { name: "노퍽섬", countryCode: "NF" },
  { name: "누벨칼레도니", countryCode: "NC" },
  { name: "뉴질랜드", countryCode: "NZ" },
  { name: "니우에", countryCode: "NU" },
  { name: "니제르", countryCode: "NE" },
  { name: "니카라과", countryCode: "NI" },

  { name: "덴마크", countryCode: "DK" },
  { name: "도미니카 공화국", countryCode: "DO" },
  { name: "도미니카 연방", countryCode: "DM" },
  { name: "독일", countryCode: "DE" },
  { name: "동티모르", countryCode: "TL" },
  { name: "라오스", countryCode: "LA" },
  { name: "라이베리아", countryCode: "LR" },
  { name: "라트비아", countryCode: "LV" },
  { name: "러시아", countryCode: "RU" },
  { name: "레바논", countryCode: "LB" },
  { name: "레소토", countryCode: "LS" },
  { name: "레위니옹", countryCode: "RE" },
  { name: "루마니아", countryCode: "RO" },
  { name: "룩셈부르크", countryCode: "LU" },
  { name: "르완다", countryCode: "RW" },
  { name: "리비아", countryCode: "LY" },
  { name: "리투아니아", countryCode: "LT" },
  { name: "리히텐슈타인", countryCode: "LI" },
  { name: "마다가스카르", countryCode: "MG" },
  { name: "마르티니크", countryCode: "MQ" },
  { name: "마셜 제도", countryCode: "MH" },
  { name: "마요트", countryCode: "YT" },
  { name: "마카오", countryCode: "MO" },
  { name: "북마케도니아", countryCode: "MK" },
  { name: "말라위", countryCode: "MW" },
  { name: "말레이시아", countryCode: "MY" },
  { name: "말리", countryCode: "ML" },
  { name: "맨섬", countryCode: "IM" },
  { name: "멕시코", countryCode: "MX" },
  { name: "모나코", countryCode: "MC" },
  { name: "모로코", countryCode: "MA" },
  { name: "모리셔스", countryCode: "MU" },
  { name: "모리타니", countryCode: "MR" },
  { name: "모잠비크", countryCode: "MZ" },
  { name: "몬테네그로", countryCode: "ME" },
  { name: "몬트세랫", countryCode: "MS" },
  { name: "몰도바", countryCode: "MD" },
  { name: "몰디브", countryCode: "MV" },
  { name: "몰타", countryCode: "MT" },
  { name: "몽골", countryCode: "MN" },
  { name: "미국", countryCode: "US" },
  { name: "미국령 군소 제도", countryCode: "UM" },
  { name: "미국령 버진아일랜드", countryCode: "VI" },
  { name: "미얀마", countryCode: "MM" },
  { name: "미크로네시아 연방", countryCode: "FM" },
  { name: "바누아투", countryCode: "VU" },
  { name: "바레인", countryCode: "BH" },
  { name: "바베이도스", countryCode: "BB" },
  { name: "바티칸 시국", countryCode: "VA" },
  { name: "바하마", countryCode: "BS" },
  { name: "방글라데시", countryCode: "BD" },
  { name: "버뮤다", countryCode: "BM" },
  { name: "베냉", countryCode: "BJ" },
  { name: "베네수엘라", countryCode: "VE" },
  { name: "베트남", countryCode: "VN" },
  { name: "벨기에", countryCode: "BE" },
  { name: "벨라루스", countryCode: "BY" },
  { name: "벨리즈", countryCode: "BZ" },
  { name: "보네르섬", countryCode: "BQ" },
  { name: "보스니아 헤르체고비나", countryCode: "BA" },
  { name: "보츠와나", countryCode: "BW" },
  { name: "볼리비아", countryCode: "BO" },
  { name: "부룬디", countryCode: "BI" },
  { name: "부르키나파소", countryCode: "BF" },
  { name: "부베섬", countryCode: "BV" },
  { name: "부탄", countryCode: "BT" },
  { name: "북마리아나 제도", countryCode: "MP" },
  { name: "불가리아", countryCode: "BG" },
  { name: "브라질", countryCode: "BR" },
  { name: "브루나이", countryCode: "BN" },
  { name: "사모아", countryCode: "WS" },
  { name: "사우디아라비아", countryCode: "SA" },
  { name: "사우스조지아 사우스샌드위치 제도", countryCode: "GS" },
  { name: "산마리노", countryCode: "SM" },
  { name: "상투메 프린시페", countryCode: "ST" },
  { name: "생마르탱", countryCode: "MF" },
  { name: "생바르텔레미", countryCode: "BL" },
  { name: "생피에르 미클롱", countryCode: "PM" },
  { name: "서사하라", countryCode: "EH" },
  { name: "세네갈", countryCode: "SN" },
  { name: "세르비아", countryCode: "RS" },
  { name: "세이셸", countryCode: "SC" },
  { name: "세인트루시아", countryCode: "LC" },
  { name: "세인트빈센트 그레나딘", countryCode: "VC" },
  { name: "세인트키츠 네비스", countryCode: "KN" },
  { name: "세인트헬레나", countryCode: "SH" },
  { name: "소말리아", countryCode: "SO" },
  { name: "솔로몬 제도", countryCode: "SB" },
  { name: "수단", countryCode: "SD" },
  { name: "수리남", countryCode: "SR" },
  { name: "스리랑카", countryCode: "LK" },
  { name: "스발바르 얀마옌 제도", countryCode: "SJ" },
  { name: "스웨덴", countryCode: "SE" },
  { name: "스위스", countryCode: "CH" },
  { name: "스페인", countryCode: "ES" },
  { name: "슬로바키아", countryCode: "SK" },
  { name: "슬로베니아", countryCode: "SI" },
  { name: "시리아", countryCode: "SY" },
  { name: "시에라리온", countryCode: "SL" },
  { name: "신트마르턴", countryCode: "SX" },
  { name: "싱가포르", countryCode: "SG" },
  { name: "아랍에미리트", countryCode: "AE" },
  { name: "아루바", countryCode: "AW" },
  { name: "아르메니아", countryCode: "AM" },
  { name: "아르헨티나", countryCode: "AR" },
  { name: "아메리칸사모아", countryCode: "AS" },
  { name: "아이슬란드", countryCode: "IS" },
  { name: "아이티", countryCode: "HT" },
  { name: "아일랜드", countryCode: "IE" },
  { name: "아제르바이잔", countryCode: "AZ" },
  { name: "아프가니스탄", countryCode: "AF" },
  { name: "안도라", countryCode: "AD" },
  { name: "알바니아", countryCode: "AL" },
  { name: "알제리", countryCode: "DZ" },
  { name: "앙골라", countryCode: "AO" },
  { name: "앤티가 바부다", countryCode: "AG" },
  { name: "앵귈라", countryCode: "AI" },
  { name: "에리트레아", countryCode: "ER" },
  { name: "에스와티니", countryCode: "SZ" },
  { name: "에스토니아", countryCode: "EE" },
  { name: "에콰도르", countryCode: "EC" },
  { name: "에티오피아", countryCode: "ET" },
  { name: "엘살바도르", countryCode: "SV" },
  { name: "영국", countryCode: "GB" },
  { name: "영국령 버진아일랜드", countryCode: "VG" },
  { name: "영국령 인도양 지역", countryCode: "IO" },
  { name: "예멘", countryCode: "YE" },
  { name: "오만", countryCode: "OM" },
  { name: "오스트레일리아", countryCode: "AU" },
  { name: "오스트리아", countryCode: "AT" },
  { name: "온두라스", countryCode: "HN" },
  { name: "올란드 제도", countryCode: "AX" },
  { name: "요르단", countryCode: "JO" },
  { name: "우간다", countryCode: "UG" },
  { name: "우루과이", countryCode: "UY" },
  { name: "우즈베키스탄", countryCode: "UZ" },
  { name: "우크라이나", countryCode: "UA" },
  { name: "왈리스 푸투나", countryCode: "WF" },
  { name: "이라크", countryCode: "IQ" },
  { name: "이란", countryCode: "IR" },
  { name: "이스라엘", countryCode: "IL" },
  { name: "이집트", countryCode: "EG" },
  { name: "이탈리아", countryCode: "IT" },
  { name: "인도", countryCode: "IN" },
  { name: "인도네시아", countryCode: "ID" },
  { name: "일본", countryCode: "JP" },
  { name: "자메이카", countryCode: "JM" },
  { name: "잠비아", countryCode: "ZM" },
  { name: "저지섬", countryCode: "JE" },
  { name: "적도 기니", countryCode: "GQ" },
  { name: "조선민주주의인민공화국", countryCode: "KP" },
  { name: "조지아", countryCode: "GE" },
  { name: "중국", countryCode: "CN" },
  { name: "중앙아프리카 공화국", countryCode: "CF" },
  { name: "지부티", countryCode: "DJ" },
  { name: "지브롤터", countryCode: "GI" },
  { name: "짐바브웨", countryCode: "ZW" },
  { name: "차드", countryCode: "TD" },
  { name: "체코", countryCode: "CZ" },
  { name: "칠레", countryCode: "CL" },
  { name: "카메룬", countryCode: "CM" },
  { name: "카보베르데", countryCode: "CV" },
  { name: "카자흐스탄", countryCode: "KZ" },
  { name: "카타르", countryCode: "QA" },
  { name: "캄보디아", countryCode: "KH" },
  { name: "캐나다", countryCode: "CA" },
  { name: "케냐", countryCode: "KE" },
  { name: "케이맨 제도", countryCode: "KY" },
  { name: "코모로", countryCode: "KM" },
  { name: "코스타리카", countryCode: "CR" },
  { name: "코코스 제도", countryCode: "CC" },
  { name: "코트디부아르", countryCode: "CI" },
  { name: "콜롬비아", countryCode: "CO" },
  { name: "콩고 공화국", countryCode: "CG" },
  { name: "콩고 민주 공화국", countryCode: "CD" },
  { name: "쿠바", countryCode: "CU" },
  { name: "쿠웨이트", countryCode: "KW" },
  { name: "쿡 제도", countryCode: "CK" },
  { name: "퀴라소", countryCode: "CW" },
  { name: "크로아티아", countryCode: "HR" },
  { name: "크리스마스섬", countryCode: "CX" },
  { name: "키르기스스탄", countryCode: "KG" },
  { name: "키리바시", countryCode: "KI" },
  { name: "키프로스", countryCode: "CY" },
  { name: "대만", countryCode: "TW" },
  { name: "타지키스탄", countryCode: "TJ" },
  { name: "탄자니아", countryCode: "TZ" },
  { name: "태국", countryCode: "TH" },
  { name: "터크스 케이커스 제도", countryCode: "TC" },
  { name: "튀르키예", countryCode: "TR" },
  { name: "토고", countryCode: "TG" },
  { name: "토켈라우", countryCode: "TK" },
  { name: "통가", countryCode: "TO" },
  { name: "투르크메니스탄", countryCode: "TM" },
  { name: "투발루", countryCode: "TV" },
  { name: "튀니지", countryCode: "TN" },
  { name: "트리니다드 토바고", countryCode: "TT" },
  { name: "파나마", countryCode: "PA" },
  { name: "파라과이", countryCode: "PY" },
  { name: "파키스탄", countryCode: "PK" },
  { name: "파푸아뉴기니", countryCode: "PG" },
  { name: "팔라우", countryCode: "PW" },
  { name: "팔레스타인", countryCode: "PS" },
  { name: "페로 제도", countryCode: "FO" },
  { name: "페루", countryCode: "PE" },
  { name: "포르투갈", countryCode: "PT" },
  { name: "포클랜드 제도", countryCode: "FK" },
  { name: "폴란드", countryCode: "PL" },
  { name: "푸에르토리코", countryCode: "PR" },
  { name: "프랑스", countryCode: "FR" },
  { name: "프랑스령 기아나", countryCode: "GF" },
  { name: "프랑스령 남방 및 남극 지역", countryCode: "TF" },
  { name: "프랑스령 폴리네시아", countryCode: "PF" },
  { name: "피지", countryCode: "FJ" },
  { name: "핀란드", countryCode: "FI" },
  { name: "필리핀", countryCode: "PH" },
  { name: "핏케언 제도", countryCode: "PN" },
  { name: "허드 맥도널드 제도", countryCode: "HM" },
  { name: "헝가리", countryCode: "HU" },
  { name: "홍콩", countryCode: "HK" },
];
